In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

In [3]:
tf.executing_eagerly()

True

In [4]:
 ?tf.feature_column.categorical_column_with_vocabulary_list

In [5]:
import numpy as np
import shutil

In [6]:
shutil.rmtree('outdir',ignore_errors=True)#start fresh every time

In [7]:
feat_cols = [
    tf.feature_column.numeric_column("sq_footage"),
    tf.feature_column.categorical_column_with_vocabulary_list('type',['apt','house'])
]

In [8]:
model = tf.estimator.LinearRegressor(feat_cols,'outdir')

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'outdir', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [9]:
def train_input_fn():
    
    features = {
        'sq_footage':[1000,2000,3000,2000,1000,3000],
        'type':['house','house','house','apt','apt','apt']
    }
    
    labels = [500,1000,3000,2000,3000,1000]
    return features, labels

In [10]:
model.train(train_input_fn,steps=1000)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
Please use `layer.add_weight` method instead.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into outdir/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 4041666.8, step = 0
INFO:tensorflow:global_step/sec: 815.288
INFO:tensorflow:loss = 1288194.9, step = 1

In [11]:
tf.executing_eagerly()

True

In [12]:
def predict_input_fn():
    
    features = {
        'sq_footage':[1000,2000,3000,2000,1000,3000],
        'type':['house','house','house','apt','apt','apt']
    }
    
    #labels = [500,1000,3000,2000,3000,1000]
    return features#, labels

In [13]:
tf.executing_eagerly()

True

In [14]:
predictions = model.predict(predict_input_fn)

In [15]:
tf.executing_eagerly()

True

### following code disables eager mode. why?

In [ ]:
# next(predictions)

# tf.executing_eagerly()

#### following line gives unlimited predictions. why?

In [ ]:
# for item in predictions:
#     print(item)

In [16]:
tf.executing_eagerly()

True

change model easily, without changing input

In [17]:
model2 = tf.estimator.DNNRegressor([30,15],feat_cols,'outdir')

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'outdir', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [18]:
model2.train(train_input_fn,steps=1000)

INFO:tensorflow:Calling model_fn.


ValueError: Items of feature_columns must be a <class 'tensorflow.python.feature_column.feature_column_v2.DenseColumn'>. You can wrap a categorical column with an embedding_column or indicator_column. Given: VocabularyListCategoricalColumn(key='type', vocabulary_list=('apt', 'house'), dtype=tf.string, default_value=-1, num_oov_buckets=0)

In [19]:
feat_cols2 = [
    tf.feature_column.numeric_column("sq_footage"),
    tf.feature_column.indicator_column(tf.feature_column.categorical_column_with_vocabulary_list('type',['apt','house']))
]

In [20]:
shutil.rmtree('outdir')

In [21]:
model2 = tf.estimator.DNNRegressor([30,15],feat_cols2,'outdir')

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'outdir', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [22]:
model2.train(train_input_fn,steps=1000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into outdir/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 2626696.2, step = 0
INFO:tensorflow:global_step/sec: 826.782
INFO:tensorflow:loss = 2107401.5, step = 100 (0.125 sec)
INFO:tensorflow:global_step/sec: 1165.07
INFO:tensorflow:loss = 1902288.1, step = 200 (0.084 sec)
INFO:tensorflow:global_step/sec: 1169.51
INFO:tensorflow:loss = 1761490.1, step = 300 (0.087 sec)
INFO:tensorflow:global_step/sec: 1213.29
INFO:tensorflow:loss = 1656244.0, step = 400 (0.083 sec)
INFO:tensorflow:global_step/sec: 1208.86
INFO:tensorflow:loss = 1574932.0, step = 500 (0.083 sec)
INFO:tensorflow:

In [23]:
pred=model2.predict(predict_input_fn)

In [24]:
tf.executing_eagerly()

True

### do not execute - turns off eager execution

In [ ]:
# print(next(pred))
# print(next(pred))
# print(next(pred))
# print(next(pred))
# print(next(pred))
# print(next(pred))

In [25]:
tf.executing_eagerly()

True

In [26]:
%ls outdir

checkpoint                        model.ckpt-0.meta
graph.pbtxt                       model.ckpt-1000.data-00000-of-00001
model.ckpt-0.data-00000-of-00001  model.ckpt-1000.index
model.ckpt-0.index                model.ckpt-1000.meta


## Read from pandas dataframe

In [27]:
import pandas as pd

In [28]:
data = {
    'sq_footage': [1000,2000,3000,2000,1000,3000],
    'type':['house','house','house','apt','apt','apt'],
    'price':[500,1000,3000,2000,3000,1000]
}



In [29]:
df=pd.DataFrame(data)

In [30]:
tf.compat.v1.estimator.inputs.pandas_input_fn

<function tensorflow_estimator.python.estimator.inputs.pandas_io.pandas_input_fn(x, y=None, batch_size=128, num_epochs=1, shuffle=None, queue_capacity=1000, num_threads=1, target_column='target')>

In [31]:
def pandas_input_fn(df):
    return tf.compat.v1.estimator.inputs.pandas_input_fn(
        df,
        df['price'],
        batch_size=128,
        num_epochs=10,
        shuffle=True,
        queue_capacity=1000)

In [32]:
shutil.rmtree('outdir')

In [33]:
model2.train(pandas_input_fn(df))

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into outdir/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 4877910.5, step = 0
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 1...
INFO:tensorflow:Saving checkpoints for 1 into outdir/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 1...
INFO:tensorflow:Loss for final step: 487791

In [34]:
%ls outdir

checkpoint                        model.ckpt-0.meta
graph.pbtxt                       model.ckpt-1.data-00000-of-00001
model.ckpt-0.data-00000-of-00001  model.ckpt-1.index
model.ckpt-0.index                model.ckpt-1.meta


In [35]:
pred=model2.predict(predict_input_fn)

In [36]:
# print(next(pred))
# print(next(pred))
# print(next(pred))
# print(next(pred))
# print(next(pred))

In [37]:
df

sq_footage   type  price
0        1000  house    500
1        2000  house   1000
2        3000  house   3000
3        2000    apt   2000
4        1000    apt   3000
5        3000    apt   1000

In [38]:
def pandas_eval_fn(df):
    return tf.compat.v1.estimator.inputs.pandas_input_fn(
        df,
        df['price'],
        batch_size=128,
        num_epochs=1,
        shuffle=False)

In [39]:
model2.evaluate(pandas_eval_fn(df))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-07-13T05:57:16Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from outdir/model.ckpt-1
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Inference Time : 0.26103s
INFO:tensorflow:Finished evaluation at 2020-07-13-05:57:16
INFO:tensorflow:Saving dict for global step 1: average_loss = 4806885.0, global_step = 1, label/mean = 1750.0, loss = 4806885.0, prediction/mean = -200.46771
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1: outdir/model.ckpt-1


{'average_loss': 4806885.0,
 'label/mean': 1750.0,
 'loss': 4806885.0,
 'prediction/mean': -200.46771,
 'global_step': 1}

In [40]:
tf.executing_eagerly()

True

## replace input fn w/ dataset

In [67]:
df.to_csv('train-1.csv',index=False,header=False)
df.to_csv('train-2.csv',index=False,header=False)

In [43]:
tf.executing_eagerly()

True

In [70]:
dataset=tf.data.Dataset.list_files('train-*.csv').flat_map(tf.data.TextLineDataset)

In [72]:
for item in dataset:
    print(item.numpy())

b'1000,house,500'
b'2000,house,1000'
b'3000,house,3000'
b'2000,apt,2000'
b'1000,apt,3000'
b'3000,apt,1000'
b'1000,house,500'
b'2000,house,1000'
b'3000,house,3000'
b'2000,apt,2000'
b'1000,apt,3000'
b'3000,apt,1000'


In [74]:
def decode_line(row):
    #convert csv columns to tensors
    cols = tf.io.decode_csv(row, record_defaults=[[0],['house'],[0]])
    
    features = {
        'sq_footage':cols[0],
        'type':cols[1]
    }
    labels =cols[2]
    
    return features, labels

In [89]:
dataset=tf.data.Dataset.list_files('train-*.csv').flat_map(tf.data.TextLineDataset).map(decode_line)

In [94]:
for item in dataset:
    print(item)

({'sq_footage': <tf.Tensor: shape=(), dtype=int32, numpy=1000>, 'type': <tf.Tensor: shape=(), dtype=string, numpy=b'house'>}, <tf.Tensor: shape=(), dtype=int32, numpy=500>)
({'sq_footage': <tf.Tensor: shape=(), dtype=int32, numpy=2000>, 'type': <tf.Tensor: shape=(), dtype=string, numpy=b'house'>}, <tf.Tensor: shape=(), dtype=int32, numpy=1000>)
({'sq_footage': <tf.Tensor: shape=(), dtype=int32, numpy=3000>, 'type': <tf.Tensor: shape=(), dtype=string, numpy=b'house'>}, <tf.Tensor: shape=(), dtype=int32, numpy=3000>)
({'sq_footage': <tf.Tensor: shape=(), dtype=int32, numpy=2000>, 'type': <tf.Tensor: shape=(), dtype=string, numpy=b'apt'>}, <tf.Tensor: shape=(), dtype=int32, numpy=2000>)
({'sq_footage': <tf.Tensor: shape=(), dtype=int32, numpy=1000>, 'type': <tf.Tensor: shape=(), dtype=string, numpy=b'apt'>}, <tf.Tensor: shape=(), dtype=int32, numpy=3000>)
({'sq_footage': <tf.Tensor: shape=(), dtype=int32, numpy=3000>, 'type': <tf.Tensor: shape=(), dtype=string, numpy=b'apt'>}, <tf.Tensor:

In [116]:
d3 = dataset.shuffle(10).repeat(2).batch(4)
list(d3.as_numpy_iterator())

[({'sq_footage': array([2000, 1000, 2000, 2000], dtype=int32),
   'type': array([b'apt', b'apt', b'house', b'house'], dtype=object)},
  array([2000, 3000, 1000, 1000], dtype=int32)),
 ({'sq_footage': array([3000, 1000, 3000, 3000], dtype=int32),
   'type': array([b'house', b'house', b'apt', b'house'], dtype=object)},
  array([3000,  500, 1000, 3000], dtype=int32)),
 ({'sq_footage': array([2000, 1000, 1000, 3000], dtype=int32),
   'type': array([b'apt', b'apt', b'house', b'apt'], dtype=object)},
  array([2000, 3000,  500, 1000], dtype=int32)),
 ({'sq_footage': array([3000, 1000, 2000, 2000], dtype=int32),
   'type': array([b'house', b'apt', b'apt', b'house'], dtype=object)},
  array([3000, 3000, 2000, 1000], dtype=int32)),
 ({'sq_footage': array([3000, 1000, 1000, 3000], dtype=int32),
   'type': array([b'apt', b'apt', b'house', b'house'], dtype=object)},
  array([1000, 3000,  500, 3000], dtype=int32)),
 ({'sq_footage': array([1000, 3000, 2000, 2000], dtype=int32),
   'type': array([b'ho

In [118]:
for item in d3:
    print(item)

({'sq_footage': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([2000, 1000, 2000, 3000], dtype=int32)>, 'type': <tf.Tensor: shape=(4,), dtype=string, numpy=array([b'apt', b'house', b'apt', b'apt'], dtype=object)>}, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([2000,  500, 2000, 1000], dtype=int32)>)
({'sq_footage': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1000, 3000, 2000, 1000], dtype=int32)>, 'type': <tf.Tensor: shape=(4,), dtype=string, numpy=array([b'apt', b'apt', b'house', b'apt'], dtype=object)>}, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([3000, 1000, 1000, 3000], dtype=int32)>)
({'sq_footage': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([3000, 2000, 1000, 3000], dtype=int32)>, 'type': <tf.Tensor: shape=(4,), dtype=string, numpy=array([b'house', b'house', b'house', b'house'], dtype=object)>}, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([3000, 1000,  500, 3000], dtype=int32)>)
({'sq_footage': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([3000, 2

In [119]:
tf.compat.v1.data.make_one_shot_iterator(d3).get_next()

({'sq_footage': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([2000, 3000, 3000, 1000], dtype=int32)>,
  'type': <tf.Tensor: shape=(4,), dtype=string, numpy=array([b'house', b'house', b'apt', b'apt'], dtype=object)>},
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1000, 3000, 1000, 3000], dtype=int32)>)

In [132]:
def input_fn_dataset():
    dataset=tf.data.Dataset.list_files('train-*.csv').flat_map(tf.data.TextLineDataset).map(decode_line)
    dataset = dataset.shuffle(10).repeat(5).batch(3)
    features, labels = tf.compat.v1.data.make_one_shot_iterator(dataset).get_next()
    return features, labels


In [133]:
input_fn_dataset()

({'sq_footage': <tf.Tensor: shape=(3,), dtype=int32, numpy=array([3000, 1000, 2000], dtype=int32)>,
  'type': <tf.Tensor: shape=(3,), dtype=string, numpy=array([b'apt', b'house', b'apt'], dtype=object)>},
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1000,  500, 2000], dtype=int32)>)

In [136]:
shutil.rmtree('outdir')

In [137]:
model3=tf.estimator.LinearRegressor(feat_cols,'outdir')

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'outdir', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [138]:
model3.train(input_fn_dataset)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into outdir/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 2000000.0, step = 0
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 20...
INFO:tensorflow:Saving checkpoints for 20 into outdir/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 20...
INFO:tensorflow:Loss for final step: 2401879.2.


In [139]:
tf.executing_eagerly()

True

In [158]:
def predict_fn_dataset():
    dataset=tf.data.Dataset.list_files('train-*.csv').flat_map(tf.data.TextLineDataset).map(decode_line)
    dataset = dataset.batch(3)
    features, _ = tf.compat.v1.data.make_one_shot_iterator(dataset).get_next()
    return features

In [159]:
preds_iter = model3.predict(predict_fn_dataset)

In [160]:
preds_iter

<generator object Estimator.predict at 0x7f2782db3250>

In [161]:
tf.executing_eagerly()

True

In [162]:
import itertools
# Read saved model and use it for prediction
#model3=tf.estimator.LinearRegressor(feat_cols,'outdir')
#preds_iter = model3.predict(input_fn = make_input_fn(df_valid, 1))
print([pred['predictions'][0] for pred in list(itertools.islice(preds_iter, 50))])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from outdir/model.ckpt-20
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
[746.33966, 1491.033, 2235.726, 1491.228, 746.5348, 2235.9214, 746.33966, 1491.033, 2235.726, 1491.228, 746.5348, 2235.9214]


In [163]:
tf.executing_eagerly()

True

### Yaay! seems to be executing eagerly again provided the ENTIRE iterator is looped over

### use train_and_evaluate for managed distributed training (using AI Platform)

#### - including parameter servers, exporting model to production


In [ ]:
shutil.rmtree('outdir')

In [173]:
#12instances *5repeat = 60instances / 3batch-size = 20 steps
tf.estimator.train_and_evaluate(model3,tf.estimator.TrainSpec(input_fn_dataset),tf.estimator.EvalSpec(input_fn_dataset))

INFO:tensorflow:Not using Distribute Coordinator.
INFO:tensorflow:Running training and evaluation locally (non-distributed).
INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps None or save_checkpoints_secs 600.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from outdir/model.ckpt-120
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 120...
INFO:tensorflow:Saving checkpoints for 120 into outdir/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 120...
INFO:tensorflow:loss = 828433.2, step = 120
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 140...
INFO:tensorflo

({'average_loss': 1288961.5,
  'label/mean': 1750.0,
  'loss': 1288961.6,
  'prediction/mean': 1518.2479,
  'global_step': 140},
 [])

### tensorboard not working

In [182]:
# %tensorboard --logdir ./outdir
# %load_ext tensorboard

## Export model

In [184]:
def serving_function():
    json = {
        'square_foot': tf.compat.v1.placeholder(tf.int32,[None]),#batch-size none
        'prop_type': tf.compat.v1.placeholder(tf.string,[None])
    }
    
    #tranformations on json data before submitting to features...
    features = {
        'sq_footage': json['square_foot'],
        'type': json['prop_type']
    }
    return tf.estimator.export.ServingInputReceiver(features,json)

In [185]:
exp = tf.estimator.LatestExporter('pricing',serving_function)

In [187]:
%ls outdir

checkpoint                          model.ckpt-140.index
graph.pbtxt                         model.ckpt-140.meta
model.ckpt-100.data-00000-of-00001  model.ckpt-60.data-00000-of-00001
model.ckpt-100.index                model.ckpt-60.index
model.ckpt-100.meta                 model.ckpt-60.meta
model.ckpt-120.data-00000-of-00001  model.ckpt-80.data-00000-of-00001
model.ckpt-120.index                model.ckpt-80.index
model.ckpt-120.meta                 model.ckpt-80.meta
model.ckpt-140.data-00000-of-00001


In [188]:
tf.estimator.train_and_evaluate(model3,tf.estimator.TrainSpec(input_fn_dataset),
                                tf.estimator.EvalSpec(input_fn_dataset,exporters=exp))

INFO:tensorflow:Not using Distribute Coordinator.
INFO:tensorflow:Running training and evaluation locally (non-distributed).
INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps None or save_checkpoints_secs 600.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from outdir/model.ckpt-140
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 140...
INFO:tensorflow:Saving checkpoints for 140 into outdir/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 140...
INFO:tensorflow:loss = 1868292.4, step = 140
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 160...
INFO:tensorfl

({'average_loss': 1288659.5,
  'label/mean': 1750.0,
  'loss': 1288659.2,
  'prediction/mean': 1523.9341,
  'global_step': 160},
 [b'outdir/export/pricing/1594644296'])

In [195]:
%%writefile test_json_local.txt
{"square_foot":1520, "prop_type": "apt"}
{"square_foot":4520, "prop_type": "house"}

Overwriting test_json_local.txt


In [196]:
!cat test_json_local.txt

{"square_foot":1520, "prop_type": "apt"}
{"square_foot":4520, "prop_type": "house"}


In [220]:
%ls ./outdir/export/pricing

1594644296/


In [219]:
%ls ./outdir/export/pricing/1594644296

saved_model.pb  variables/


#### https://stackoverflow.com/questions/48824381/gcloud-ml-engine-local-predict-runtimeerror-bad-magic-number-in-pyc-file

In [217]:
%%bash
find "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine" -name '*.pyc' -delete

In [218]:
!gcloud ai-platform local predict --model-dir ./outdir/export/pricing/1594644296 --json-instances test_json_local.txt --signature-name predict

Instructions for updating:
non-resource variables are not supported in the long term
2020-07-13 13:07:37.526526: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-07-13 13:07:37.526570: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-07-13 13:07:37.526613: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (10937550f8c5): /proc/driver/nvidia/version does not exist
2020-07-13 13:07:37.526968: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-13 13:07:37.535482: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2300000000 Hz
2020-07-13 13:07:37.535781: I tensorflow/compiler/xla/service/service.cc:168]