In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

In [3]:
tf.executing_eagerly()

True

In [4]:
 ?tf.feature_column.categorical_column_with_vocabulary_list

In [4]:
import numpy as np
import shutil

In [5]:
shutil.rmtree('outdir',ignore_errors=True)#start fresh every time

In [6]:
feat_cols = [
    tf.feature_column.numeric_column("sq_footage"),
    tf.feature_column.categorical_column_with_vocabulary_list('type',['apt','house'])
]

In [7]:
model = tf.estimator.LinearRegressor(feat_cols,'outdir')

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'outdir', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [8]:
def train_input_fn():
    
    features = {
        'sq_footage':[1000,2000,3000,2000,1000,3000],
        'type':['house','house','house','apt','apt','apt']
    }
    
    labels = [500,1000,3000,2000,3000,1000]
    return features, labels

In [9]:
model.train(train_input_fn,steps=1000)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
Please use `layer.add_weight` method instead.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into outdir/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 4041666.8, step = 0
INFO:tensorflow:global_step/sec: 811.365
INFO:tensorflow:loss = 1288194.9, step = 1

In [10]:
tf.executing_eagerly()

True

In [11]:
def predict_input_fn():
    
    features = {
        'sq_footage':[1000,2000,3000,2000,1000,3000],
        'type':['house','house','house','apt','apt','apt']
    }
    
    #labels = [500,1000,3000,2000,3000,1000]
    return features#, labels

In [12]:
tf.executing_eagerly()

True

In [13]:
predictions = model.predict(predict_input_fn)

In [14]:
tf.executing_eagerly()

True

### following code disables eager mode. why?

In [ ]:
# next(predictions)

# tf.executing_eagerly()

#### following line gives unlimited predictions. why?

In [ ]:
# for item in predictions:
#     print(item)

In [16]:
tf.executing_eagerly()

True

change model easily, without changing input

In [15]:
model2 = tf.estimator.DNNRegressor([30,15],feat_cols,'outdir')

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'outdir', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [18]:
model2.train(train_input_fn,steps=1000)

INFO:tensorflow:Calling model_fn.


ValueError: Items of feature_columns must be a <class 'tensorflow.python.feature_column.feature_column_v2.DenseColumn'>. You can wrap a categorical column with an embedding_column or indicator_column. Given: VocabularyListCategoricalColumn(key='type', vocabulary_list=('apt', 'house'), dtype=tf.string, default_value=-1, num_oov_buckets=0)

In [16]:
feat_cols2 = [
    tf.feature_column.numeric_column("sq_footage"),
    tf.feature_column.indicator_column(tf.feature_column.categorical_column_with_vocabulary_list('type',['apt','house']))
]

In [17]:
shutil.rmtree('outdir')

In [18]:
model2 = tf.estimator.DNNRegressor([30,15],feat_cols2,'outdir')

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'outdir', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [19]:
model2.train(train_input_fn,steps=1000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into outdir/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 4759700.5, step = 0
INFO:tensorflow:global_step/sec: 818.906
INFO:tensorflow:loss = 3884981.2, step = 100 (0.124 sec)
INFO:tensorflow:global_step/sec: 1190.43
INFO:tensorflow:loss = 3544172.0, step = 200 (0.086 sec)
INFO:tensorflow:global_step/sec: 1169.6
INFO:tensorflow:loss = 3322413.8, step = 300 (0.085 sec)
INFO:tensorflow:global_step/sec: 1191.31
INFO:tensorflow:loss = 3148164.0, step = 400 (0.084 sec)
INFO:tensorflow:global_step/sec: 1027.14
INFO:tensorflow:loss = 3002597.8, step = 500 (0.096 sec)
INFO:tensorflow:g

In [20]:
pred=model2.predict(predict_input_fn)

In [21]:
tf.executing_eagerly()

True

### do not execute - turns off eager execution

In [ ]:
# print(next(pred))
# print(next(pred))
# print(next(pred))
# print(next(pred))
# print(next(pred))
# print(next(pred))

In [25]:
tf.executing_eagerly()

True

In [22]:
%ls outdir

checkpoint                        model.ckpt-0.meta
graph.pbtxt                       model.ckpt-1000.data-00000-of-00001
model.ckpt-0.data-00000-of-00001  model.ckpt-1000.index
model.ckpt-0.index                model.ckpt-1000.meta


## Read from pandas dataframe

In [23]:
import pandas as pd

In [24]:
data = {
    'sq_footage': [1000,2000,3000,2000,1000,3000],
    'type':['house','house','house','apt','apt','apt'],
    'price':[500,1000,3000,2000,3000,1000]
}



In [25]:
df=pd.DataFrame(data)

In [26]:
tf.compat.v1.estimator.inputs.pandas_input_fn

<function tensorflow_estimator.python.estimator.inputs.pandas_io.pandas_input_fn(x, y=None, batch_size=128, num_epochs=1, shuffle=None, queue_capacity=1000, num_threads=1, target_column='target')>

In [27]:
def pandas_input_fn(df):
    return tf.compat.v1.estimator.inputs.pandas_input_fn(
        df,
        df['price'],
        batch_size=128,
        num_epochs=10,
        shuffle=True,
        queue_capacity=1000)

In [28]:
shutil.rmtree('outdir')

In [29]:
model2.train(pandas_input_fn(df))

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into outdir/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 6177142.0, step = 0
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 1...
INFO:tensorflow:Saving checkpoints for 1 into outdir/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 1...
INFO:tensorflow:Loss for final step: 617714

In [30]:
%ls outdir

checkpoint                        model.ckpt-0.meta
graph.pbtxt                       model.ckpt-1.data-00000-of-00001
model.ckpt-0.data-00000-of-00001  model.ckpt-1.index
model.ckpt-0.index                model.ckpt-1.meta


In [31]:
pred=model2.predict(predict_input_fn)

In [36]:
# print(next(pred))
# print(next(pred))
# print(next(pred))
# print(next(pred))
# print(next(pred))

In [32]:
df

sq_footage   type  price
0        1000  house    500
1        2000  house   1000
2        3000  house   3000
3        2000    apt   2000
4        1000    apt   3000
5        3000    apt   1000

In [33]:
def pandas_eval_fn(df):
    return tf.compat.v1.estimator.inputs.pandas_input_fn(
        df,
        df['price'],
        batch_size=128,
        num_epochs=1,
        shuffle=False)

In [34]:
model2.evaluate(pandas_eval_fn(df))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-07-14T17:33:29Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from outdir/model.ckpt-1
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Inference Time : 0.28715s
INFO:tensorflow:Finished evaluation at 2020-07-14-17:33:29
INFO:tensorflow:Saving dict for global step 1: average_loss = 6072704.5, global_step = 1, label/mean = 1750.0, loss = 6072704.5, prediction/mean = -488.96054
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1: outdir/model.ckpt-1


{'average_loss': 6072704.5,
 'label/mean': 1750.0,
 'loss': 6072704.5,
 'prediction/mean': -488.96054,
 'global_step': 1}

In [35]:
tf.executing_eagerly()

True

## replace input fn w/ dataset

In [36]:
df.to_csv('train-1.csv',index=False,header=False)
df.to_csv('train-2.csv',index=False,header=False)

In [37]:
tf.executing_eagerly()

True

In [38]:
dataset=tf.data.Dataset.list_files('train-*.csv').flat_map(tf.data.TextLineDataset)

In [39]:
for item in dataset:
    print(item.numpy())

b'1000,house,500'
b'2000,house,1000'
b'3000,house,3000'
b'2000,apt,2000'
b'1000,apt,3000'
b'3000,apt,1000'
b'1000,house,500'
b'2000,house,1000'
b'3000,house,3000'
b'2000,apt,2000'
b'1000,apt,3000'
b'3000,apt,1000'


In [40]:
def decode_line(row):
    #convert csv columns to tensors
    cols = tf.io.decode_csv(row, record_defaults=[[0],['house'],[0]])
    
    features = {
        'sq_footage':cols[0],
        'type':cols[1]
    }
    labels =cols[2]
    
    return features, labels

In [41]:
dataset=tf.data.Dataset.list_files('train-*.csv').flat_map(tf.data.TextLineDataset).map(decode_line)

In [42]:
for item in dataset:
    print(item)

({'sq_footage': <tf.Tensor: shape=(), dtype=int32, numpy=1000>, 'type': <tf.Tensor: shape=(), dtype=string, numpy=b'house'>}, <tf.Tensor: shape=(), dtype=int32, numpy=500>)
({'sq_footage': <tf.Tensor: shape=(), dtype=int32, numpy=2000>, 'type': <tf.Tensor: shape=(), dtype=string, numpy=b'house'>}, <tf.Tensor: shape=(), dtype=int32, numpy=1000>)
({'sq_footage': <tf.Tensor: shape=(), dtype=int32, numpy=3000>, 'type': <tf.Tensor: shape=(), dtype=string, numpy=b'house'>}, <tf.Tensor: shape=(), dtype=int32, numpy=3000>)
({'sq_footage': <tf.Tensor: shape=(), dtype=int32, numpy=2000>, 'type': <tf.Tensor: shape=(), dtype=string, numpy=b'apt'>}, <tf.Tensor: shape=(), dtype=int32, numpy=2000>)
({'sq_footage': <tf.Tensor: shape=(), dtype=int32, numpy=1000>, 'type': <tf.Tensor: shape=(), dtype=string, numpy=b'apt'>}, <tf.Tensor: shape=(), dtype=int32, numpy=3000>)
({'sq_footage': <tf.Tensor: shape=(), dtype=int32, numpy=3000>, 'type': <tf.Tensor: shape=(), dtype=string, numpy=b'apt'>}, <tf.Tensor:

In [43]:
d3 = dataset.shuffle(10).repeat(2).batch(4)
list(d3.as_numpy_iterator())

[({'sq_footage': array([2000, 2000, 1000, 1000], dtype=int32),
   'type': array([b'house', b'apt', b'apt', b'apt'], dtype=object)},
  array([1000, 2000, 3000, 3000], dtype=int32)),
 ({'sq_footage': array([3000, 3000, 2000, 2000], dtype=int32),
   'type': array([b'house', b'house', b'apt', b'house'], dtype=object)},
  array([3000, 3000, 2000, 1000], dtype=int32)),
 ({'sq_footage': array([3000, 1000, 1000, 3000], dtype=int32),
   'type': array([b'apt', b'house', b'house', b'apt'], dtype=object)},
  array([1000,  500,  500, 1000], dtype=int32)),
 ({'sq_footage': array([2000, 1000, 2000, 1000], dtype=int32),
   'type': array([b'apt', b'house', b'apt', b'apt'], dtype=object)},
  array([2000,  500, 2000, 3000], dtype=int32)),
 ({'sq_footage': array([3000, 1000, 3000, 1000], dtype=int32),
   'type': array([b'apt', b'apt', b'house', b'house'], dtype=object)},
  array([1000, 3000, 3000,  500], dtype=int32)),
 ({'sq_footage': array([2000, 3000, 3000, 2000], dtype=int32),
   'type': array([b'hous

In [44]:
for item in d3:
    print(item)

({'sq_footage': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([3000, 3000, 2000, 3000], dtype=int32)>, 'type': <tf.Tensor: shape=(4,), dtype=string, numpy=array([b'house', b'apt', b'apt', b'house'], dtype=object)>}, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([3000, 1000, 2000, 3000], dtype=int32)>)
({'sq_footage': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1000, 2000, 1000, 1000], dtype=int32)>, 'type': <tf.Tensor: shape=(4,), dtype=string, numpy=array([b'house', b'house', b'house', b'apt'], dtype=object)>}, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 500, 1000,  500, 3000], dtype=int32)>)
({'sq_footage': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([2000, 2000, 3000, 1000], dtype=int32)>, 'type': <tf.Tensor: shape=(4,), dtype=string, numpy=array([b'apt', b'house', b'apt', b'apt'], dtype=object)>}, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([2000, 1000, 1000, 3000], dtype=int32)>)
({'sq_footage': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1000, 1

In [45]:
tf.compat.v1.data.make_one_shot_iterator(d3).get_next()

({'sq_footage': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1000, 2000, 3000, 2000], dtype=int32)>,
  'type': <tf.Tensor: shape=(4,), dtype=string, numpy=array([b'house', b'apt', b'apt', b'house'], dtype=object)>},
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 500, 2000, 1000, 1000], dtype=int32)>)

In [46]:
def input_fn_dataset():
    dataset=tf.data.Dataset.list_files('train-*.csv').flat_map(tf.data.TextLineDataset).map(decode_line)
    dataset = dataset.shuffle(10).repeat(5).batch(3)
    features, labels = tf.compat.v1.data.make_one_shot_iterator(dataset).get_next()
    return features, labels


In [47]:
input_fn_dataset()

({'sq_footage': <tf.Tensor: shape=(3,), dtype=int32, numpy=array([2000, 2000, 3000], dtype=int32)>,
  'type': <tf.Tensor: shape=(3,), dtype=string, numpy=array([b'apt', b'apt', b'apt'], dtype=object)>},
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([2000, 2000, 1000], dtype=int32)>)

In [48]:
shutil.rmtree('outdir')

In [49]:
model3=tf.estimator.LinearRegressor(feat_cols,'outdir')

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'outdir', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [50]:
model3.train(input_fn_dataset)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into outdir/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 1750000.0, step = 0
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 20...
INFO:tensorflow:Saving checkpoints for 20 into outdir/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 20...
INFO:tensorflow:Loss for final step: 3898068.2.


In [51]:
tf.executing_eagerly()

True

In [52]:
def predict_fn_dataset():
    dataset=tf.data.Dataset.list_files('train-*.csv').flat_map(tf.data.TextLineDataset).map(decode_line)
    dataset = dataset.batch(3)
    features, _ = tf.compat.v1.data.make_one_shot_iterator(dataset).get_next()
    return features

In [53]:
preds_iter = model3.predict(predict_fn_dataset)

In [54]:
preds_iter

<generator object Estimator.predict at 0x7f4438670350>

In [55]:
tf.executing_eagerly()

True

In [56]:
import itertools
# Read saved model and use it for prediction
#model3=tf.estimator.LinearRegressor(feat_cols,'outdir')
#preds_iter = model3.predict(input_fn = make_input_fn(df_valid, 1))
print([pred['predictions'][0] for pred in list(itertools.islice(preds_iter, 50))])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from outdir/model.ckpt-20
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
[750.45557, 1499.399, 2248.3425, 1499.617, 750.67346, 2248.5605, 750.45557, 1499.399, 2248.3425, 1499.617, 750.67346, 2248.5605]


In [57]:
tf.executing_eagerly()

True

### Yaay! seems to be executing eagerly again provided the ENTIRE iterator is looped over

### use train_and_evaluate for managed distributed training (using AI Platform)

#### - including parameter servers, exporting model to production


In [58]:
shutil.rmtree('outdir')

In [59]:
#12instances *5repeat = 60instances / 3batch-size = 20 steps
tf.estimator.train_and_evaluate(model3,tf.estimator.TrainSpec(input_fn_dataset),tf.estimator.EvalSpec(input_fn_dataset))

INFO:tensorflow:Not using Distribute Coordinator.
INFO:tensorflow:Running training and evaluation locally (non-distributed).
INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps None or save_checkpoints_secs 600.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into outdir/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 7333333.5, step = 0
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 20...
INFO:tensorflow:Saving checkpoints for 20 into outdir/model.ckpt.
INFO:tensorflow:Call

({'average_loss': 1304564.9,
  'label/mean': 1750.0,
  'loss': 1304565.0,
  'prediction/mean': 1422.1251,
  'global_step': 20},
 [])

### tensorboard not working

In [182]:
# %tensorboard --logdir ./outdir
# %load_ext tensorboard

## Export model

In [60]:
def serving_function():
    json = {
        'square_foot': tf.compat.v1.placeholder(tf.int32,[None]),#batch-size none
        'prop_type': tf.compat.v1.placeholder(tf.string,[None])
    }
    
    #tranformations on json data before submitting to features...
    features = {
        'sq_footage': json['square_foot'],
        'type': json['prop_type']
    }
    return tf.estimator.export.ServingInputReceiver(features,json)

In [61]:
exp = tf.estimator.LatestExporter('pricing',serving_function)

In [62]:
%ls outdir

checkpoint                        model.ckpt-0.meta
graph.pbtxt                       model.ckpt-20.data-00000-of-00001
model.ckpt-0.data-00000-of-00001  model.ckpt-20.index
model.ckpt-0.index                model.ckpt-20.meta


In [63]:
tf.estimator.train_and_evaluate(model3,tf.estimator.TrainSpec(input_fn_dataset),
                                tf.estimator.EvalSpec(input_fn_dataset,exporters=exp))

INFO:tensorflow:Not using Distribute Coordinator.
INFO:tensorflow:Running training and evaluation locally (non-distributed).
INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps None or save_checkpoints_secs 600.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from outdir/model.ckpt-20
Instructions for updating:
Use standard file utilities to get mtimes.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 20...
INFO:tensorflow:Saving checkpoints for 20 into outdir/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 20...
INFO:tensorflow:loss = 3917622.8, step = 20
INFO:tensorflow:Calling c

({'average_loss': 1290662.4,
  'label/mean': 1750.0,
  'loss': 1290662.5,
  'prediction/mean': 1501.046,
  'global_step': 40},
 [b'outdir/export/pricing/1594748082'])

In [64]:
%%writefile test_json_local.txt
{"square_foot":1520, "prop_type": "apt"}
{"square_foot":4520, "prop_type": "house"}

Writing test_json_local.txt


In [65]:
!cat test_json_local.txt

{"square_foot":1520, "prop_type": "apt"}
{"square_foot":4520, "prop_type": "house"}


In [66]:
%ls ./outdir/export/pricing

1594748082/


In [68]:
%ls ./outdir/export/pricing/1594748082

saved_model.pb  variables/


#### https://stackoverflow.com/questions/48824381/gcloud-ml-engine-local-predict-runtimeerror-bad-magic-number-in-pyc-file

In [69]:
%%bash
find "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine" -name '*.pyc' -delete

In [70]:
!gcloud ai-platform local predict --model-dir ./outdir/export/pricing/1594748082 --json-instances test_json_local.txt --signature-name predict

Instructions for updating:
non-resource variables are not supported in the long term
2020-07-14 17:35:59.496275: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-07-14 17:35:59.496320: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-07-14 17:35:59.496362: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (10937550f8c5): /proc/driver/nvidia/version does not exist
2020-07-14 17:35:59.496676: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-14 17:35:59.507177: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2300000000 Hz
2020-07-14 17:35:59.508258: I tensorflow/compiler/xla/service/service.cc:168]

In [74]:
%ls ./outdir/export/pricing/1594748082

saved_model.pb  variables/


In [80]:
import os
estimator_base_path = os.path.join('outdir', 'from_estimator')
estimator_path = model3.export_saved_model(estimator_base_path, serving_function)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Signatures INCLUDED in export for Classify: None
INFO:tensorflow:Signatures INCLUDED in export for Regress: None
INFO:tensorflow:Signatures INCLUDED in export for Predict: ['predict']
INFO:tensorflow:Signatures INCLUDED in export for Train: None
INFO:tensorflow:Signatures INCLUDED in export for Eval: None
INFO:tensorflow:Signatures EXCLUDED from export because they cannot be be served via TensorFlow Serving APIs:
INFO:tensorflow:'serving_default' : Regression input must be a single string Tensor; got {'square_foot': <tf.Tensor 'Placeholder:0' shape=(None,) dtype=int32>, 'prop_type': <tf.Tensor 'Placeholder_1:0' shape=(None,) dtype=string>}
INFO:tensorflow:'regression' : Regression input must be a single string Tensor; got {'square_foot': <tf.Tensor 'Placeholder:0' shape=(None,) dtype=int32>, 'prop_type': <tf.Tensor 'Placeholder_1:0' shape=(None,) dtype=string>}
INFO:tensorflow:Restoring parameters 

In [81]:
%ls outdir/from_estimator/

1594749219/  1594749233/  1594749236/  1594749239/


In [82]:
estimator_path

b'outdir/from_estimator/1594749239'

In [83]:
imported = tf.saved_model.load(estimator_path)

In [114]:
imported.signatures["predict"](square_foot=tf.constant([1234]),prop_type=tf.constant([b'apt']))

{'predictions': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[927.0974]], dtype=float32)>}

In [118]:
imported.signatures["predict"](square_foot=tf.constant([1234,4567,10000]),prop_type=tf.constant(['apt','house','apt']))

{'predictions': <tf.Tensor: shape=(3, 1), dtype=float32, numpy=
 array([[ 927.0974],
        [3424.9175],
        [7497.5728]], dtype=float32)>}